### PR TITLE
confined kube-apiserver

### PR DESCRIPTION
**Pull request by wwwtyro**

### CODE REVIEW

**Comment by marcoceppi** [comment]
Was this all that was actually needed?

**Comment by wwwtyro** [comment]
@marcoceppi for the snap, probably yes more or less. There's more to do on the master layer: https://github.com/wwwtyro/kubernetes/commit/c677c37d5455fcb3831cdc568ca159f4df6acf44

... but that's just barely limping along right now.

For the snap, if we want to make a it a standalone thing, we'll need to deal with other stuff of course, like getting it working as a daemon that interops with our master layer.

**Comment by marcoceppi** [comment]
I'm just talking about the snap portion.

**Comment by wwwtyro** [comment]
@marcoceppi there might be more there - we're still working through bugs

**Comment by Cynerva** [comment]
Confinement works great. Merging. More to come!

**Pull request merged**
